polling_interval_sec = 5

[inverter]
username = "user"
password = ""
url = "http://your-inverter-ip"

[influx]
url = "http://your-influxdb.com"
port = 8086
db = "influx-db"
user = "root"
password = ""