polling_interval_sec = 5

[[inverters]]
inverter.username = "user"
inverter.password = ""
inverter.url = "http://your-inverter-ip"
influx_id = "pvwr"

[[inverters]]
inverter.username = "user2"
inverter.password = ""
inverter.url = "http://your-inverter-ip"
influx_id = "pvwr2"

[influx]
url = "http://your-influxdb.com"
port = 8086
db = "influx-db"
user = "root"
password = ""